" My vim config
" Gaby Czegany <Glabsounet@gmail.com>

" General {{{
set hidden
set showcmd
set nocompatible
set ruler
set scrolloff=5
set mouse=a
set shortmess=atI
set t_Co=256
set rtp+=~/.vim/bundle/Vundle.vim
set completeopt-=preview
" }}}

" Search {{{
set hlsearch
set ignorecase
set smartcase
" }}}

" Plugins {{{
filetype off
call vundle#begin()
Bundle 'gmarik/Vundle.vim'
Bundle 'godlygeek/tabular'
Bundle 'pbrisbin/html-template-syntax'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'mileszs/ack.vim'
Bundle 'Valloric/YouCompleteMe'
"let g:ycm_seed_identifiers_with_syntax = 0
let g:ycm_add_preview_to_completeopt=0
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"
call vundle#end()
" }}}

" Filetype {{{
filetype on
filetype plugin on
filetype indent on
" }}}

" Tabs {{{
set tabstop=8
set softtabstop=4
set shiftwidth=4
set smarttab
set noexpandtab
set smartindent
" }}}

" Colors {{{
syntax on
colorscheme desert_custom
" }}}

runtime mappings.vim
