" My vim config
" Gaby Czegany <Glabsounet@gmail.com>

" General {{{
set hidden
set showcmd
set nocompatible
set ruler
set scrolloff=5
set mouse=a
set shortmess=atI
set t_Co=256
set rtp+=~/.vim/bundle/vundle/
" }}}

" Search {{{
set hlsearch
set ignorecase
set smartcase
" }}}

" Plugins {{{
filetype off
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'godlygeek/tabular'
Bundle 'pbrisbin/html-template-syntax'
Bundle 'Lokaltog/vim-easymotion'
" }}}

" Filetype {{{
filetype on
filetype plugin on
filetype indent on
" }}}

" Tabs {{{
set tabstop=8
set softtabstop=4
set shiftwidth=4
set smarttab
set noexpandtab
set smartindent
" }}}

" Colors {{{
syntax on
colorscheme desert_custom
" }}}

runtime mappings.vim
