" My vim config
" Gaby Czegany <Glabsounet@gmail.com>

" {{{ General
execute pathogen#infect()
set ruler
set mouse=a
set shortmess=atI
set hidden
set showcmd
" }}}

" {{{ Filetype 
filetype on
filetype plugin on
filetype indent on
" }}}

" {{{ Search
set hlsearch
set ignorecase
set smartcase
" }}}

" {{{ Tabs
set tabstop=8
set softtabstop=4
set shiftwidth=4
set smarttab
set noexpandtab
set smartindent
" }}}

" {{{ Colors
syntax on
colorscheme desert_custom
"}}}

runtime mappings.vim
